"""Config-key coverage: every simulator knob is either declared, gated, or a known gap.

The reference configuration that E1-C4/E2-C4 actually runs is a 47-key
``politeia.cfg`` generated by the experiment driver, while ``config.cpp`` accepts
185 keys. The other 138 therefore take their values from the C++ in-class
initializers, and nothing in the repository said which of those 138 are harmless
and which are live. That is the same structural gap that produced S16/S17/S18:
a channel nobody rejected at the entrance can be active without anyone noticing.

This module makes the inventory mechanical. It parses the parser keys out of
``config.cpp``, derives the effective default of each field from ``config.hpp``,
generates the reference ``politeia.cfg`` with the driver itself, and then
requires **every** parser key to fall in exactly one audited category:

* declared in the reference cfg,
* gated by a module switch the reference cfg pins to ``false``,
* superseded by the IC file or by an untaken code branch,
* a sentinel/alias, or a field with no consumer at all,
* or a **documented gap**: reachable and non-neutral while undeclared.

Adding a new knob to ``config.cpp`` without classifying it fails test 1, so the
audit cannot silently fall behind the code. The remaining tests pin the
assumptions the table rests on (switches stay off, generated keys stay declared,
the two recorded gaps keep their exact default values). Everything here is
static: it reads C++/Python sources and writes only into ``tmp_path``.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
import re
import sys

import pytest

REPO_ROOT = Path(__file__).parents[1]
SIMULATOR_SRC = "research/src/experiments/politeia/src"
CONFIG_CPP = f"{SIMULATOR_SRC}/core/config.cpp"
CONFIG_HPP = f"{SIMULATOR_SRC}/core/config.hpp"
CONSTANTS_HPP = f"{SIMULATOR_SRC}/core/constants.hpp"
IC_LOADER = f"{SIMULATOR_SRC}/io/ic_loader.cpp"
MAIN_CPP = f"{SIMULATOR_SRC}/main.cpp"

MODULE_PATH = REPO_ROOT / "research" / "src" / "experiments" / "run_landscape_study.py"
sys.path.insert(0, str(MODULE_PATH.parent))
_SPEC = importlib.util.spec_from_file_location("run_landscape_study", MODULE_PATH)
assert _SPEC and _SPEC.loader
run_landscape_study = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(run_landscape_study)

# The authorized confirmatory experiment: its generated cfg *is* the reference
# configuration the numerical calibration and the parameter lock describe.
REFERENCE_EXPERIMENT = "E1-MATCHED-LANDSCAPES-C4"

# --------------------------------------------------------------------------
# Audited categories for keys that are NOT declared in the reference cfg.
# --------------------------------------------------------------------------

# Consumed only inside a block guarded by a switch that the reference cfg sets
# to false. The switch is re-checked for real in
# `test_reference_cfg_pins_every_gating_switch_off`.
GATED_BY_SWITCH: dict[str, tuple[str, ...]] = {
    "culture_enabled": (
        "assimilation_rate",
        "repulsion_threshold",
        "repulsion_strength",
        "attraction_strength",
        "culture_mate_threshold",
    ),
    "reproduction_enabled": (
        "puberty_age",
        "menopause_age",
        "peak_fertility_age",
        "max_fertility",
        "gestation_time",
        "nursing_time",
        "mate_range",
        "wealth_birth_cost",
        "min_wealth_to_breed",
        "mutation_strength",
        "culture_mutation_scale",
        "epsilon_mutation_scale",
        "fertility_alpha",
        "gender_enabled",
        "sex_ratio",
        "male_cooldown",
        "max_partners_per_cooldown",
        "partner_wealth_factor",
        "inheritance_model",
        "epsilon_patrilineal_threshold",
        "culture_dominant_weight",
    ),
    "mortality_enabled": (
        "gompertz_alpha",
        "gompertz_beta",
        "max_age",
        "accident_rate",
        "survival_threshold",
        "starvation_sigmoid_k",
        "lifespan_wealth_enabled",
        "lifespan_wealth_k",
        "lifespan_wealth_ref",
        "lifespan_wealth_beta_alpha",
        "lifespan_tech_enabled",
        "lifespan_tech_k",
        "lifespan_tech_ref",
        "lifespan_tech_beta_alpha",
    ),
    "technology_enabled": (
        "tech_drift_rate",
        "tech_spread_rate",
        "tech_jump_base_rate",
        "tech_jump_knowledge_scale",
        "tech_jump_magnitude",
        "wealth_jump_rate_pos",
        "wealth_jump_rate_neg",
        "wealth_jump_fraction",
    ),
    "loyalty_enabled": (
        "loyalty_protection_gain",
        "loyalty_tax_drain",
        "loyalty_culture_penalty",
        "loyalty_noise_sigma",
        "tax_rate",
        "tax_efficiency",
        "rebel_threshold",
        "switch_threshold",
        "attachment_threshold",
        "initial_loyalty",
        "succession_loyalty_factor",
        "succession_heir_loyalty_cap",
        "max_hierarchy_depth",
        "hierarchy_assimilation_rate",
        "hierarchy_repair_interval",
        # Only consumer is the flow network, and `need_network` is
        # `loyalty_enabled && ...` (main.cpp:753-756).
        "network_window_factor",
    ),
    "conquest_enabled": (
        "conquest_power_ratio",
        "conquest_base_prob",
        "conquest_initial_loyalty",
        "war_cost_enabled",
        "war_cost_attacker",
        "war_cost_defender",
        "war_casualties_enabled",
        "war_casualty_rate",
        "pillage_enabled",
        "pillage_fraction",
        "deterrence_enabled",
        "deterrence_ratio",
    ),
    "plague_enabled": (
        "n_pathogens",
        "plague_trigger_density",
        "plague_trigger_rate",
        "plague_infection_radius",
        "plague_infection_rate",
        "plague_base_mortality",
        "plague_recovery_time",
        "plague_immunity_inheritance",
    ),
    "carrying_capacity_enabled": (
        "carrying_capacity_base",
        # `DENSITY_UPDATE_INTERVAL` only guards the cached_density/cached_K
        # block, which is itself inside `if (cfg.carrying_capacity_enabled)`.
        "density_update_interval",
    ),
    "climate_enabled": (
        "climate_production_enabled",
        "climate_carrying_enabled",
        "climate_mortality_enabled",
        "climate_mortality_scale",
        "climate_friction_enabled",
        "climate_friction_scale",
        "climate_plague_enabled",
        "climate_plague_scale",
        "climate_mode",
        "climate_time_mode",
        "climate_file",
        "climate_drift_rate",
        "climate_drift_schedule",
        "climate_season_amplitude",
        "climate_season_period",
        "climate_update_interval",
    ),
    "river_enabled": (
        "river_file",
        "river_format",
        "river_mode",
        "river_grid_rows",
        "river_grid_cols",
        "river_type",
        "river_resource_enabled",
        "river_resource_strength",
        "river_resource_alpha",
        "river_capacity_enabled",
        "river_capacity_strength",
        "river_capacity_beta",
        "river_exchange_enabled",
        "river_exchange_strength",
        "river_tech_enabled",
        "river_tech_strength",
        "river_plague_enabled",
        "river_plague_strength",
        "river_force_enabled",
        "river_force_scale",
    ),
    "terrain_barrier_enabled": ("terrain_barrier_scale",),
}

# Superseded by the IC file: the loader finds the column and never falls back.
IC_SUPERSEDED = (
    "init_jitter_factor",  # only the no-IC-file grid placement branch
    "init_age_min",  # `age` column is present; `age_pyramid` is false
    "init_age_max",
    "age_pyramid",
    "initial_wealth",  # `w` column is present
)

# Reachable only on a branch the reference cfg does not take (binary terrain,
# or checkpointing which `checkpoint_interval = 0` disables).
BRANCH_INERT = (
    "terrain_grid_rows",
    "terrain_grid_cols",
    "checkpoint_dir",
    "restart_file",
)

# Negative sentinel resolving to a declared value (`interaction_range`).
SENTINEL = ("exchange_cutoff",)

# Parsed and stored, but no consumer anywhere in `src/`.
NO_CONSUMER = (
    "mpi_px",
    "mpi_py",
)

# Legacy alias: setting it writes both declared terrain scales.
LEGACY_ALIAS = ("terrain_scale",)

# --------------------------------------------------------------------------
# Documented gaps (S19). Reachable and non-neutral while undeclared, so the
# reference cfg does not determine the run on its own: the binary's in-class
# default is load-bearing. Recorded, not hidden; each is anchored to the code
# line that makes it live in `test_effective_defaults_keep_their_anchors`.
# --------------------------------------------------------------------------
EFFECTIVE_UNDECLARED: dict[str, tuple[str, str]] = {
    # (C++ default, why it is live)
    "density_radius": (
        "5.0",
        "sets cell_cutoff = max(interaction_range, density_radius, exchange "
        "cutoff) unconditionally (main.cpp:246-253), i.e. the cell-list "
        "geometry that determines the pair enumeration order of the serial "
        "in-place exchange kernel",
    ),
    "culture_dim": (
        "constants::DEFAULT_CULTURE_DIM",
        "the IC CSV has no c* columns, so the loader draws N(0,1) per "
        "dimension per particle from the same RNG that supplies the initial "
        "momenta (ic_loader.cpp:138-143,167-172): the effective initial "
        "momenta depend on an undeclared dimension",
    ),
}


def _read(relative: str) -> str:
    return (REPO_ROOT / relative).read_text(encoding="utf-8")


def _parser_keys() -> set[str]:
    return set(re.findall(r'key == "([a-z0-9_]+)"', _read(CONFIG_CPP)))


def _field_defaults() -> dict[str, str]:
    fields = re.findall(
        r"^\s{4}([A-Za-z_:<>0-9 ]+?)\s+([A-Za-z0-9_]+)\s*=\s*([^;]+);",
        _read(CONFIG_HPP),
        re.M,
    )
    return {name: default.strip() for _, name, default in fields}


def _key_to_field() -> dict[str, str]:
    return dict(
        re.findall(r'key == "([a-z0-9_]+)"\)\s*cfg\.([A-Za-z0-9_]+)', _read(CONFIG_CPP))
    )


def _reference_config_values(tmp_path, monkeypatch) -> dict[str, str]:
    """Generate the reference cfg the way the driver does, and parse it."""
    monkeypatch.setattr(run_landscape_study, "PROJECT_ROOT", tmp_path)
    config = {
        "seeds": [11],
        "population": 16,
        "grid_shape": [16, 16],
        "bounds": [0.0, 100.0, 0.0, 100.0],
        "dt": 0.005,
        "total_time": 1.0,
        "output_time_interval": 0.5,
        "temperature": 0.5,
        "friction": 1.0,
        "social_strength": 0.0,
        "exchange_rate": 0.5,
        "exchange_noise_strength": 0.05,
        "exchange_reversion_rate": 1.0,
        "epsilon_log_sigma": 0.5,
        "wealth_decay_rate": 0.02,
        "base_production": 0.01,
        "mean_wealth": 5.0,
        "terrain_production_scale": 1.0,
        "terrain_force_scale": 1.0,
        "strict_numerics": True,
        "confirmative_mode": True,
    }
    specs = run_landscape_study.prepare_inputs(
        REFERENCE_EXPERIMENT, config, tmp_path / "reference"
    )
    assert specs, "the driver produced no run specs"
    cfg_path = run_landscape_study.project_path(specs[0]["cpp_config"])
    values: dict[str, str] = {}
    for line in cfg_path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    return values


@pytest.fixture(scope="module")
def reference_cfg(tmp_path_factory):
    """Generated once; the generator is pure with respect to the repo."""
    return _reference_config_values(
        tmp_path_factory.mktemp("config-coverage"), pytest.MonkeyPatch()
    )


def _classified() -> dict[str, str]:
    """key -> category, for every key outside the reference cfg."""
    table: dict[str, str] = {}
    for switch, keys in GATED_BY_SWITCH.items():
        for key in keys:
            table[key] = f"gated:{switch}"
    for key in IC_SUPERSEDED:
        table[key] = "ic-superseded"
    for key in BRANCH_INERT:
        table[key] = "branch-inert"
    for key in SENTINEL:
        table[key] = "sentinel"
    for key in NO_CONSUMER:
        table[key] = "no-consumer"
    for key in LEGACY_ALIAS:
        table[key] = "legacy-alias"
    for key in EFFECTIVE_UNDECLARED:
        table[key] = "effective-undeclared"
    return table


def test_every_parser_key_is_classified_exactly_once(reference_cfg):
    parser_keys = _parser_keys()
    table = _classified()
    declared = set(reference_cfg)

    assert len(table) == len(set(table)), "a key is classified twice"
    assert declared <= parser_keys, (
        "the driver emits a cfg key the simulator cannot parse: "
        f"{sorted(declared - parser_keys)}"
    )
    assert declared.isdisjoint(table), (
        "a key is both declared in the reference cfg and filed under an "
        f"inert/gap category: {sorted(declared & set(table))}"
    )
    unclassified = parser_keys - declared - set(table)
    assert not unclassified, (
        "new simulator knob(s) without an audited category -- decide whether "
        f"the reference cfg declares them or which switch gates them: "
        f"{sorted(unclassified)}"
    )
    stale = set(table) - parser_keys
    assert not stale, f"audit table lists keys config.cpp does not parse: {sorted(stale)}"


def test_reference_cfg_pins_every_gating_switch_off(reference_cfg):
    for switch in GATED_BY_SWITCH:
        assert switch in reference_cfg, (
            f"{switch} is the gate for {len(GATED_BY_SWITCH[switch])} audited "
            "keys but the reference cfg does not pin it"
        )
        assert reference_cfg[switch] == "false", (
            f"{switch} is not false in the reference cfg, so every key filed "
            "under it is reachable and the audit must be redone"
        )


def test_no_gated_or_gap_key_is_emitted_by_the_driver(reference_cfg):
    table = _classified()
    emitted = sorted(set(table) & set(reference_cfg))
    assert not emitted, (
        "the driver now emits keys the audit filed as inert/gap; either the "
        f"gap is closed (update the table) or the build is inconsistent: {emitted}"
    )


def test_effective_defaults_keep_their_anchors(reference_cfg):
    defaults = _field_defaults()
    key_to_field = _key_to_field()
    constants = _read(CONSTANTS_HPP)

    # The recorded gaps must stay undeclared: pinning one would change whether
    # the reference cfg determines the run, and that change has to be deliberate.
    for key in EFFECTIVE_UNDECLARED:
        assert key not in reference_cfg, f"{key} is now declared in the cfg"

    density_default = defaults[key_to_field["density_radius"]]
    assert density_default == EFFECTIVE_UNDECLARED["density_radius"][0], (
        "density_radius changed default; the recorded cell geometry (and thus "
        "the exchange pair order) changed with it"
    )
    assert (
        "std::max(cfg.interaction_range, cfg.density_radius)"
        in _read(MAIN_CPP)
    ), "the density_radius -> cell_cutoff coupling moved; re-audit the gap"

    culture_default = defaults[key_to_field["culture_dim"]]
    assert culture_default == "constants::DEFAULT_CULTURE_DIM"
    assert re.search(r"DEFAULT_CULTURE_DIM\s*=\s*2\s*;", constants), (
        "DEFAULT_CULTURE_DIM changed; the number of N(0,1) draws the IC loader "
        "consumes per particle changed with it"
    )
    assert "dist_cv(rng)" in _read(IC_LOADER), (
        "the IC loader no longer draws a fallback culture vector; re-audit "
        "how many RNG values a missing c* column consumes"
    )


def test_shared_and_declared_keys_are_never_filed_as_gated(reference_cfg):
    # Several knobs feed two parameter structs at once (e.g.
    # `culture_mate_threshold` goes to both the mating and the culture struct,
    # `interaction_range` to force, exchange, reproduction and culture). A key
    # is only filed as gated when *every* consumer sits behind that switch, so
    # Several knobs feed two parameter structs at once: `interaction_range`
    # goes to force, exchange, reproduction and culture, so it is declared;
    # `culture_mate_threshold` goes to mating *and* culture, both of which the
    # reference cfg switches off, so filing it under one switch is sound.
    table = _classified()
    for key in ("interaction_range", "exchange_rate"):
        assert key in reference_cfg
        assert key not in table, f"{key} has a consumer outside its switch"
    assert all(
        switch in ("culture_enabled", "reproduction_enabled")
        for switch, keys in GATED_BY_SWITCH.items()
        if "culture_mate_threshold" in keys
    )

    for switch, keys in GATED_BY_SWITCH.items():
        assert keys, f"{switch} gates nothing"
        assert len(keys) == len(set(keys)), f"{switch} lists a key twice"
